### ISSUE TITLE
Question about the envoy config file

### ISSUE THREAD

**Issue by zhaohuabing** [crazyxy/envoy-example#1]
Hi @yxue,

We have been come out the same idea of HTTP inspector and use it in our istio environment to split HTTP and TCP traffic, so it's nice to see this feature has been officially supported by Istio. 

When I look into the envoy config file (envoy-example/inspector-new/client-envoy.yaml), I'm wondering why do we need the 8000 listener? It seems that all the traffic is redirected to 15001, and then go through the original destination cluster. Will the 15001 listener hands over requests to 8000?  And how if it does?

Thanks!

**Comment by yxue** [comment]
The Envoy configuration generated by Istio doesn’t require the other
inbound listeners except for 15001 (or 15006?) if user config the proxy to
capture all traffic. We could do the optimization in the future to remove
redundant listeners.

The configuration in this repo is for testing standalone Envoy which
doesn’t have any ip table intercept and redirect.
